Repository covid19cuba/covid19cuba-app, pull requests merged in 2020-03, with the labels that each got.

#4 Update README.md
  LICENSE
  README.md
Labels: documentation

#8 Create CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#16 Improve implementation
  assets/images/logo.png
  lib/src/app.dart
  lib/src/models/data_model.dart
  lib/src/models/day_model.dart
  lib/src/pages/home_page.dart
  lib/src/utils/app_theme.dart
  lib/src/utils/constants.dart
  lib/src/utils/utils.dart
  lib/src/widgets/distribution_age_groups_diagnosed.dart
  lib/src/widgets/distribution_nationality_diagnosed_widget.dart
  lib/src/widgets/error_widget.dart
  lib/src/widgets/evolution_widget.dart
  lib/src/widgets/home_drawer.dart
  lib/src/widgets/home_widget.dart
  lib/src/widgets/loading_widget.dart
  lib/src/widgets/pie_contagion_widget.dart
  lib/src/widgets/pie_sex_widget.dart
  lib/src/widgets/resume_widget.dart
  lib/src/widgets/widgets.dart
  pubspec.yaml
Labels: bug, feature

#43 Add Introduction Screens
  assets/images/advice1.png
  assets/images/advice2.png
  assets/images/advice3.png
  lib/src/app.dart
  lib/src/pages/on_boarding_page.dart
  lib/src/pages/pages.dart
  lib/src/utils/constants.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#67 Implement explicit button for refresh info data
  GALLERY.md
  gallery/image_1.jpg
  gallery/image_10.jpg
  gallery/image_11.jpg
  gallery/image_12.jpg
  gallery/image_2.jpg
  gallery/image_3.jpg
  gallery/image_4.jpg
  gallery/image_5.jpg
  gallery/image_6.jpg
  gallery/image_7.jpg
  gallery/image_8.jpg
  gallery/image_9.jpg
  lib/src/pages/home_page.dart
Labels: feature

#68 Implement link for Telegram Bot in drawer menu
  lib/src/widgets/home_drawer_widget.dart
Labels: feature
